version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
    container_name: my_server
    ports:
      - "5001:5001" # Mappa la porta del sistema host con la porta del container
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app # Monta l'intera cartella server
    depends_on:
      - db

  client:
    build:
      context: ./client
    container_name: my_client
    ports:
      - "5173:5173" # Espone la porta 5173 per il client Vite
    volumes:
      - ./client:/usr/src/app # Monta la cartella del client
    depends_on:
      - server

volumes:
  mongo_data:
