version: '3.8'

services:
  # Database MongoDB
  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo_data:/data/db
    networks:
      - my-network

  # Server
  server:
    image: fraalbi24/se2-kiruna-explorer-19-server:final
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    environment:
      - DOCKER_ENV=true
    networks:
      - my-network

  # Client (Vite con build)
  client:
    image: fraalbi24/se2-kiruna-explorer-19-client:final
    container_name: client
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - my-network

  # CDN
  cdn:
    image: fraalbi24/se2-kiruna-explorer-19-cdn:final
    container_name: cdn
    ports:
      - "3004:3004"
    depends_on:
      - server
    environment:
      - DOCKER_ENV=true
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
