name: Build and Push Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login a Docker Registry (Docker Hub o GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build e push dell'immagine 1
      - name: Build and Push CDN Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t fraalbi24/se2-kiruna-explorer-19-cdn:dev \
            --push ./cdn

      # Step 5: Build e push dell'immagine 2
      - name: Build and Push Server Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t fraalbi24/se2-kiruna-explorer-19-server:dev \
            --push ./server

      # Step 6: Build e push dell'immagine 3
      - name: Build and Push Client Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t fraalbi24/se2-kiruna-explorer-19-client:dev \
            --push ./client
