name: Integration Tests with Postman

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Avvia i servizi con Docker Compose
      - name: Start services with Docker Compose
        run: docker compose -f docker-compose.local.yml up -d --build

      # 3. Aspetta che le porte dei server siano attive
      - name: Wait for servers
        run: |
          echo "Waiting for servers to start..."
          while ! nc -z localhost 5001 || ! nc -z localhost 3004; do
            echo "Servers not ready. Retrying..."
            sleep 5
          done

      # 4. Installa Newman
      - name: Install Newman
        run: npm install -g newman

      # 5. Esegui i test Postman e salva il report
      - name: Run Postman Tests
        run: |
          newman run server/integration/sprint2/API Documentation - KIRUNA Explorer.postman_collection.json \
            --reporters cli,json,html \
            --reporter-json-export reports/newman-report.json \
            --reporter-html-export reports/newman-report.html

      # 6. Carica i report come artefatti
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-reports
          path: reports/

      # 7. Ferma i servizi Docker
      - name: Stop Docker services
        run: docker-compose -f docker-compose.local.yml down
